/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author USER
 */
public class CoursepanelGUI extends javax.swing.JPanel {

    /**
     * Creates new form CoursepanelGUI
     */
    public CoursepanelGUI() {
        initComponents();
        addbtn.setSVGImage("com/image/add.svg", 30, 30);
        editbtn.setSVGImage("com/image/edit.svg", 30, 30);
        deletebtn.setSVGImage("com/image/delete.svg", 30, 30);
        viewbtn.setSVGImage("com/image/visibility.svg", 30, 30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        addbtn = new com.gui.svgImage();
        jComboBox1 = new javax.swing.JComboBox<>();
        editbtn = new com.gui.svgImage();
        deletebtn = new com.gui.svgImage();
        viewbtn = new com.gui.svgImage();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã khóa", "Tên khóa", "Số tín", "Mã khoa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 480));

        jLabel1.setText("Tìm kiếm");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 50, 25));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 160, 25));

        addbtn.setText("svgImage1");
        add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 276, 30, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã khóa" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, -1, -1));

        editbtn.setText("svgImage2");
        add(editbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 324, 30, 30));

        deletebtn.setText("svgImage3");
        add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 372, 30, 30));

        viewbtn.setText("svgImage4");
        add(viewbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 420, 30, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.gui.svgImage addbtn;
    private com.gui.svgImage deletebtn;
    private com.gui.svgImage editbtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private com.gui.svgImage viewbtn;
    // End of variables declaration//GEN-END:variables
}
