package GUI;

import java.awt.GridLayout;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class MainmenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form Mainmenu
     */
    public MainmenuGUI() {
        initComponents();
        logo.setSVGImage("com/image/layers.svg", 30, 30);
        addstudent.setSVGImage("com/image/graduate.svg",35, 35);
        addinstructor.setSVGImage("com/image/teacher.svg", 35, 35);
        svgcourse.setSVGImage("com/image/programming.svg", 30, 30);
        svgdivide.setSVGImage("com/image/separation.svg", 30, 30);
        svgresult.setSVGImage("com/image/exam.svg", 30, 30);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        coursebtn = new javax.swing.JPanel();
        svgcourse = new com.gui.svgImage();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        svgdivide = new com.gui.svgImage();
        jLabel4 = new javax.swing.JLabel();
        resultbtn = new javax.swing.JPanel();
        svgresult = new com.gui.svgImage();
        jLabel2 = new javax.swing.JLabel();
        addstudent = new com.gui.svgImage();
        addinstructor = new com.gui.svgImage();
        mainPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        logo = new com.gui.svgImage();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        coursebtn.setBackground(new java.awt.Color(0, 204, 255));
        coursebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        coursebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coursebtnMouseClicked(evt);
            }
        });
        coursebtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        svgcourse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        svgcourse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        coursebtn.add(svgcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Khóa học");
        coursebtn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 160, -1));

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        svgdivide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        svgdivide.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel3.add(svgdivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Phân công");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 50, 160, -1));

        resultbtn.setBackground(new java.awt.Color(0, 204, 255));
        resultbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resultbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultbtnMouseClicked(evt);
            }
        });
        resultbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        svgresult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        svgresult.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resultbtn.add(svgresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Kết quả");
        resultbtn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 160, -1));

        addstudent.setText("svgImage2");

        addinstructor.setText("svgImage3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(coursebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(addstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addinstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(coursebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resultbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addinstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 160, 480));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 1120, 480));

        jPanel4.setBackground(new java.awt.Color(0, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setText("svgImage1");
        jPanel4.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Name of app");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultbtnMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.revalidate();
        mainPanel.repaint();
        ResultpanelGUI Resultpanel = new ResultpanelGUI();
        mainPanel.setLayout(new GridLayout(1,1));
        mainPanel.add(Resultpanel);
    }//GEN-LAST:event_resultbtnMouseClicked

    private void coursebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursebtnMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.revalidate();
        mainPanel.repaint();
        CoursepanelGUI Coursepanel = new CoursepanelGUI();
        mainPanel.setLayout(new GridLayout(1,1));
        mainPanel.add(Coursepanel);
    }//GEN-LAST:event_coursebtnMouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.revalidate();
        mainPanel.repaint();
        DividepanelGUI Dividepanel = new DividepanelGUI();
        mainPanel.setLayout(new GridLayout(1,1));
        mainPanel.add(Dividepanel);
    }//GEN-LAST:event_jPanel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainmenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainmenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainmenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainmenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainmenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.gui.svgImage addinstructor;
    private com.gui.svgImage addstudent;
    private javax.swing.JPanel coursebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private com.gui.svgImage logo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel resultbtn;
    private com.gui.svgImage svgcourse;
    private com.gui.svgImage svgdivide;
    private com.gui.svgImage svgresult;
    // End of variables declaration//GEN-END:variables
}
