/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import javax.swing.JFrame;

/**
 *
 * @author USER
 */
public class ResultpanelGUI extends javax.swing.JPanel {

    /**
     * Creates new form Resultpanel
     */
    public ResultpanelGUI() {
        initComponents();
        addstu.setSVGImage("com/image/add.svg", 30, 30);
        editstu.setSVGImage("com/image/edit.svg", 30, 30);
        deletestu.setSVGImage("com/image/delete.svg", 30, 30);
        viewstu.setSVGImage("com/image/visibility.svg", 30, 30);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        stuTable = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        addstu = new com.gui.svgImage();
        editstu = new com.gui.svgImage();
        deletestu = new com.gui.svgImage();
        viewstu = new com.gui.svgImage();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stuTable.setAutoCreateRowSorter(true);
        stuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã khóa", "Mã học sinh", "Điểm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(stuTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 480));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã khóa" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, -1, -1));

        jLabel1.setText("Tìm kiếm");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 50, 25));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 160, 25));

        addstu.setText("svgImage1");
        add(addstu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 276, 30, 30));

        editstu.setText("svgImage1");
        add(editstu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 324, 30, 30));

        deletestu.setText("svgImage1");
        add(deletestu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 372, 30, 30));

        viewstu.setText("svgImage1");
        add(viewstu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 420, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.gui.svgImage addstu;
    private com.gui.svgImage deletestu;
    private com.gui.svgImage editstu;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable stuTable;
    private com.gui.svgImage viewstu;
    // End of variables declaration//GEN-END:variables
}
